version: "3"

services:

  backend:
    container_name: protein-search-backend
    build:
      context: ./backend
    stdin_open: true      
    restart: always
    volumes: 
        - "./backend:/app"
        - "./backend/requirements.txt:/app/requirements.txt"
    ports:
      - "8020:8020"

  frontend:
    container_name: protein-search-frontend
    build: 
      context: ./frontend
    stdin_open: true
    restart: always
    volumes: 
      - "./frontend:/app"
      - "./frontend/requirements.txt:/app/requirements.txt"    
    ports:
      - "8501:8501"
    depends_on:
      - "backend"